### ISSUE TITLE
Help building project?

### ISSUE THREAD

**Issue by CloudNiner** [newmarcel/KeepingYouAwake#10]
Attempted to build the debug scheme after checking out with --recursive to get the Sparkle dependency but the project fails to build, unable to find the Sparkle.framework file. It appears to be looking for it in a very random location, and I was having trouble updating that location.
```
~/Library/Developer/Xcode/DerivedData/KeepingYouAwake-apbqcjufkliladgytieudutryeno/Build/Products/Debug/Sparkle.framework
```

I've only done iOS dev but would like to contribute to this, as it looks and works great! Maybe I'm missing something silly?

**Comment by newmarcel** [comment]
I changed the way Sparkle is integrated into the project in the master branch. I'm now using [Carthage](https://github.com/Carthage/Carthage) as dependency manager, which works great.

This should make building the project a bit easier :smiley:
