### ISSUE TITLE
Icon in the menu bar not very intuitive

### ISSUE THREAD

**Issue by RajDotKapoor** [newmarcel/KeepingYouAwake#100]
Icon in the menubar is not quite indicative if the KYA is active or not. I would really need to know the app to tell if it is active. If the menu bar is light vs. dark, the icon could be with or black depending on if it is active or not.

Suggestion: Add steam in the icon to indicate it is active.

**Comment by ckesc** [comment]
Maybe my icon is what you want?
https://github.com/ckesc/KeepingYouAwake_icon_fillCup

**Comment by newmarcel** [comment]
I'm sorry, I won't change the icon in the forseeable future. Please have a look at this page to see how you can install a custom icon: https://github.com/newmarcel/KeepingYouAwake/wiki/Custom-Icons
