### ISSUE TITLE
KYA prevents screensaver or turning off display

### ISSUE THREAD

**Issue by e40** [newmarcel/KeepingYouAwake#102]
So, I usually manually "Put Display to Sleep" with a hot corner.

I have my screensaver configured to come on at 20 min.

I have the Energy Saver configuration set to "Turn display off after" 20 min.

When KYA is running and active, the display never blanks.

I'm running 10.12.6, 2013 Pro.

Is this a feature or bug?  I could swear in the past (long ago, probably), it used to work.  Problem is, I came home from work yesterday and because I had forgotten to put the display to sleep, it was on for like 8 hours.

Thanks.

EDIT: I want to be clear: I want the display off, the computer on.

**Comment by e40** [comment]
Perhaps I don't even need KYA... if I turn on "Prevent computer from sleeping automatically when the display is off" and set the display to turn off after 10 minutes ... what do y'all think?  Would macOS ever sleep?

**Comment by alexandreleroux** [comment]
In my experience, KYA does not prevent the macOS screensaver from working, but yes, it does prevent the display from turning off. That's actually the main feature of KYA! Does that help?

**Comment by e40** [comment]
Yeah, turns out I don't need KYA.  Sorry for the noise.
