### ISSUE TITLE
[BUG] Doesn't memorize the Start at Login setting

### ISSUE THREAD

**Issue by schurig** [newmarcel/KeepingYouAwake#103]
Since the last release I noticed on both of my macs that are both running the latest version of macOS that the `Start at Login` setting is not memorized.

Now whenever I turn on my Mac it won't go to sleep. When I disable the `Start at Login` setting and close the app and reopen it, then it still has the checkbox in it.

![screen_shot_2018-09-03_at_10_56_36](https://user-images.githubusercontent.com/2672413/44977396-2ced2a00-af68-11e8-83bf-a49837469834.jpg)

**Comment by demiurg** [comment]
Thats interesting. Not happening for me on OSX 10.14 Beta (18A384a)

Whats your OSX version exactly?

**Comment by schurig** [comment]
They're both on 10.13.6. Not sure if the build number is the same though since it's a different model. The one I'm using right now has build number `17G65`.

What I just noticed is that the app is listed twice in the Startup apps in my user settings:

![screen_shot_2018-09-11_at_16_50_45](https://user-images.githubusercontent.com/2672413/45368052-eee4ab80-b5e2-11e8-956e-f4edcc87a3c6.jpg)

**Comment by demiurg** [comment]
I think thats a good explanation, you could have two different apps overriding the setting somehow. If you could find the second app, or remove both from startup apps, it might work?

**Comment by schurig** [comment]
@demiurg I just removed both of them and now it seems to work. So maybe during the update process something went wrong and the old settings were still there. I'll close this issue. :)

**Comment by neongrau** [comment]
Not sure if related but suspecting. For me KeepingYouAwake always started up, but always turned off though my settings specified to Activate on Launch and time indefinitely. I've now tried through various settings changes and reboots. And yet it still doesn't start up active ever.
