### ISSUE TITLE
Remove Indefinitely option

### ISSUE THREAD

**Issue by blackberryhell** [newmarcel/KeepingYouAwake#105]
Hi

Firstly great app. secondly I wanted to create a version where the max time the user could select is 30 mins (it's to allow users to do presentations) could you point to the files I would need to change to achieve this please.

Regards

Alex

**Comment by newmarcel** [comment]
You can open `KeepingYouAwake/Base.lproj/MainMenu.xib` in Xcode and remove all unneeded durations from the `Activate for Duration` menu.

Also these are hardcoded in the `General` preferences pane. You can edit the list in `KeepingYouAwake/Preferences/General/KYAGeneralPreferencesViewController.m`, starting line 28.

I hope that helps 😃

**Comment by blackberryhell** [comment]
It does, thanks so much Marcel.

**Comment by newmarcel** [comment]
Great 🎉 Have fun!
