### ISSUE TITLE
Automatically activate "Do Not Disturb" mode

### ISSUE THREAD

**Issue by enricorotundo** [newmarcel/KeepingYouAwake#106]
This will prevent notifications to appear during presentations

**Comment by newmarcel** [comment]
For me personally, _Do not disturb_ and _Keeping my Mac awake_ are two separate tasks with no direct relation. Some presentation apps like Keynote already enable DnD by default while presenting. You can also always option-click on the Notification Center icon in the top right corner of the menubar to disable notifications. This means I won't implement this feature.

Time-based DnD control could even be an idea for an entirely separate app 😃

Thanks anyway for the suggestion!
