### ISSUE TITLE
Screen never sleeps

### ISSUE THREAD

**Issue by buzzy** [newmarcel/KeepingYouAwake#115]
Does this keep the screen from sleeping too? I just want it to keep the macbook from going to sleep mode, not the screen. Is there a way to do that?

**Comment by buzzy** [comment]
Cool! Looks like there is a way! Can I change the parameters that KeepingYouAwake sends to caffeinate in some way?

**Comment by dadiyang** [comment]
I need this feature too! Thanks for adding it.

**Comment by buzzy** [comment]
I guess this will never happen. I see that there is an issue opened the wants the same thing from 2014... https://github.com/newmarcel/KeepingYouAwake/issues/12
