### ISSUE TITLE
Start at Login launcher gets removed immediately

### ISSUE THREAD

**Issue by ckotte** [newmarcel/KeepingYouAwake#117]
When I enable the checkbox, the launcher will be created:
```
# launchctl list | grep KeepingYouAwake                                                                                                                         
-	0	info.marcel-dierkes.KeepingYouAwake.Launcher
19206	0	info.marcel-dierkes.KeepingYouAwake.75096
```

As soon as I close the preferences window, the launcher gets removed and the checkbox is disabled:
```
# launchctl list | grep KeepingYouAwake                                                                                                                                                                    
19206	0	info.marcel-dierkes.KeepingYouAwake.75096
```

I don't have any KeepYouAwake Login Item anymore. I already deleted it some reboots ago.

MacOS version: 10.13.6

**Comment by insanesvk** [comment]
I don't have this problem, MacOS version: 10.14.2, the launcher is working fine for me:

```
launchctl list | grep KeepingYouAwake
-	0	info.marcel-dierkes.KeepingYouAwake.Launcher
720	0	info.marcel-dierkes.KeepingYouAwake.8988
```

**Comment by MitchellCash** [comment]
I'm not having this exact issue, but could be related.

After a restart KeepingYouAwake is not launching. The Launcher still exists after a restart here:

```
$ launchctl list | grep KeepingYouAwake
-	78	info.marcel-dierkes.KeepingYouAwake.Launcher
```

But I am having to manually open the app each restart.

**Comment by newmarcel** [comment]
Closed. The upcoming version 1.6.4 will change how "Start at Login" is implemented on macOS Ventura. Hopefully this resolves any issues.

Please create a new GitHub issue if these problems persist when this version is released.
