### ISSUE TITLE
Cannot update 1.5.0pre -> 1.5.0

### ISSUE THREAD

**Issue by 1oglop1** [newmarcel/KeepingYouAwake#118]
Hi for some reason the app got stuck during the automatic update 
![image](https://user-images.githubusercontent.com/7480694/52462132-13cd5280-2b72-11e9-881f-c2abd00480cc.png)
Is there any log I can provide or anything to help debug?

**Comment by newmarcel** [comment]
Sadly that's a known issue. I made a mistake in 1.5.0 versions older than beta 2 so they are not able to install updates. I fixed the problem in beta 2 and the final release.

You can simply redownload the [stable 1.5.0 release](https://github.com/newmarcel/KeepingYouAwake/tree/1.5.0) and hopefully this problem will be resolved.
