### ISSUE TITLE
Preferences not saving

### ISSUE THREAD

**Issue by Cranial** [newmarcel/KeepingYouAwake#120]
KeepingYouAwake version 1.50
macOS 10.14.3

Every time I restart the app it defaults to "Start at Login: off" , "Default Activation Duration: Indefinitely" and "Enable Experimental notification centre: off"

I've tried removing the app, deleting anything I could find in Library (containers). No fix.

**Comment by niklasbabel** [comment]
I have the same issue. 
KeepingYouAwake Version 1.5.0 (1050004)
macOS 10.14.3 (18D109)

**Comment by Cranial** [comment]
Any news on this issue? I as yet have not figured out a way to resolve it.

**Comment by newmarcel** [comment]
That's very strange and I haven't seen this behavior yet. This could be a weird sandboxing edge case.

I can also just guess here and recommend deleting all preferences in the following locations:

```
~/Library/Containers/info.marcel-dierkes.KeepingYouAwake
(~/Library/Preferences/info.marcel-dierkes.KeepingYouAwake.plist)
(~/Library/Application Support/KeepingYouAwake)
```

**Also please reboot your Mac before you launch the app again**.

And a related follow-up question: Did you attempt to launch the app from a location outside of `/Applications` while this problem occured?

**Comment by Cranial** [comment]
I managed to track down the cause and solution to this issue. It appeared I had KeepingYouAwake installed as a normal app install on one machine, and via Homebrew on another machine. Due to some old experimenting with preference syncing, there was a collision of preference files and locations.

I haven't got the exact locations or how I actually fixed it, due to travelling and computer changes, but removing both the app, and any homebrew references and restarting/re-installing should fix the issue.

**Comment by zisoft** [comment]
I got a new MacBook last week and now I have the same problem.

Completely uninstalled/reinstalled the app via homebrow does not change this. The preferences are not saved.

**Comment by Cranial** [comment]
Did you restore anything to the new Mac from an old one? Or use something like [mackup](https://github.com/lra/mackup) to sync/restore preferences to the new Mac?

I'm pretty sure it was mackup causing the issue for me.

**Comment by zisoft** [comment]
Yes, I transferred my settings via Mackup.

I have made some further tests:

1. Uninstall: `brew uninstall keepingyouawake`
2. deleted all files/directories:

```
~/Library/Containers/info.marcel-dierkes.KeepingYouAwake
~/Library/Preferences/info.marcel-dierkes.KeepingYouAwake.plist
~/Library/Application Support/KeepingYouAwake
```
3. Re-install: `brew install keepingyouawake`
4. Start KeepingYouAwake
5. Set my preferences: Start on login, default time to 1h

Now I check the files/directories with the following result:

`~/Library/Containers/info.marcel-dierkes.KeepingYouAwake` EXISTS
`~/Library/Containers/info.marcel-dierkes.KeepingYouAwake.Launcher` EXISTS
`~/Library/Application Support/KeepingYouAwake` DOES NOT EXIST
`~/Library/Preferences/info.marcel-dierkes.KeepingYouAwake.plist`DOES NOT EXIST

**Comment by zisoft** [comment]
Another reboot of the Mac solved the problem, although:

`~/Library/Containers/info.marcel-dierkes.KeepingYouAwake` EXISTS
`~/Library/Containers/info.marcel-dierkes.KeepingYouAwake.Launcher` EXISTS
`~/Library/Application Support/KeepingYouAwake` DOES NOT EXIST
`~/Library/Preferences/info.marcel-dierkes.KeepingYouAwake.plist`DOES NOT EXIST

**Comment by newmarcel** [comment]
Only the `~/Library/Containers/` subfolders should exist. That's alright. The last two paths are from the time before the app was sandboxed and these files can be discarded.
