### ISSUE TITLE
Feature Request: Scheduled activation

### ISSUE THREAD

**Issue by jstevensen** [newmarcel/KeepingYouAwake#121]
I would like to suggest a non critical feature that may be useful to some users. The idea is to add the ability to schedule activations (i.e. 8:00 AM - 5:00 PM) to keep a computer on during working hours. It would be nice to set this once in the morning, and not worry about the computer sleeping or staying awake all night after I've stepped away for the day. 

Another way to accomplish this would be to add an 8 and possibly 10 hour option to the default activation times. The Indefinite setting is too long, and 5 hours isn't enough. 

Thank you in advance for all of your work on KeepingYouAwake.

**Comment by kyleinprogress** [comment]
+1 

Being able to schedule the activation time period would be really nice.

**Comment by AndrWeisR** [comment]
I'd be looking for exactly this too. I'd like to keep the screen on during work hours only, and save power overnight.

**Comment by newmarcel** [comment]
While I won't add the ability to add scheduled durations, I can confirm that I will add the ability to fully customize the list of activation durations in the next release.

Thanks for the suggestion and your patience 👍
