### ISSUE TITLE
Start at login, not starting at login

### ISSUE THREAD

**Issue by MitchellCash** [newmarcel/KeepingYouAwake#124]
I have the `Start at login` preference checked, but after each restart I am having to still manually start the app.

I have tried just simply selecting/de-selecting the button, but still requires manual starting after each restart.

The Launcher still exists after a restart here:

```
$ launchctl list | grep KeepingYouAwake
-	78	info.marcel-dierkes.KeepingYouAwake.Launcher
```

I'm running:

```
System Version: macOS 10.14.4 (18E226)
Kernel Version: Darwin 18.5.0
Secure Virtual Memory: Enabled
System Integrity Protection: Enabled
```

Please let me know if there is anything else I can provide to you to help debug this issue.

**Comment by Ghostavio** [comment]
I'm having the same issue.

**Comment by newmarcel** [comment]
Closed. The upcoming version 1.6.4 will change how "Start at Login" is implemented on macOS Ventura. Hopefully this resolves any issues.

Please create a new GitHub issue if these problems persist when this version is released.
