### ISSUE TITLE
Dropping macOS Yosemite and El Capitan Support

### ISSUE THREAD

**Issue by newmarcel** [newmarcel/KeepingYouAwake#126]
I'm currently planning to drop support for macOS Yosemite (10.10) and macOS El Capitan (10.11) with the upcoming 1.6.0 feature release. These older versions limit me during development because I cannot use features like *Storyboard references* or `NSGridView`. Also it takes significantly more time to release a new version if I have to test the increasing amount of supported macOS releases.

Because I don't use user tracking and metrics frameworks *(I highly value user privacy and hate avoidable size and performance costs)* in KeepingYouAwake, I don't know what macOS versions are currently in use.

If you are still relying on macOS Yosemite and El Capitan, **please respond to this issue with your current use case**. This feedback is greatly appreciated.

Based on this feedback I can decide between multiple outcomes:

#### Scenario 1) macOS Sierra (10.12) as Minimum Deployment Target
There are no user complaints and I can safely drop Yosemite and El Capitan.

*This is my preferred outcome to avoid the maintenance burden of older macOS releases.*

#### Scenario 2) Maintain an Older Compatibility Release
I will drop Yosemite and El Capitan support for release 1.6.0 and greater.
I will declare version 1.5.x *(or even 1.4.x?)* as compatibility branch and make sure it stays compatible with Yosemite and El Capitan. No new features will be backported.

*This is a compromise, but would be doable if necessary.*

#### Scenario 3) Keep the macOS Yosemite Support
There are many user complaints and I need to keep supporting Yosemite and El Capitan.
I will continue supporting these macOS releases. The number of known issues for these macOS versions will likely increase and and the development time for new features and releases will *stay* slow.

*This is my least preferred outcome. There is already the next major macOS version on the horizon.*

---

Thank you for your feedback!

**Comment by alexandreleroux** [comment]
+1 for dropping support (Scenario 1).

The current KYA version will continue working for 10.10 & 11.11 users, no? Thus impact is likely minimal/inexistant. Software can't support legacy Oses forever!

Thanks :-)

**Comment by camlloyd** [comment]
+1 for Scenario 1 (macOS Mojave 10.14.4 user). 
The only thing preventing me fully adopting KYA is the ```Start at Login``` issue #124.

Curious to see votes for Scenarios 2 & 3.

**Comment by ideaman924** [comment]
+1 for Scenario 1. Most Macs (sans some extremely old models) can run High Sierra. If they really need KYA they can always download the last compatible version or use `caffeinate`.

**Comment by gelosi** [comment]
As long, as older versions will be compiled and available for download – it's fine to go with `scenario 1`

**Comment by henriquedesousa** [comment]
I'm still using Yosemite on my laptop, but since 1.4 is working fine since ages, as long as I can have a download link for older version I see no issues in dropping support in 1.6. Besides, I'm a Linux user and this Mac is only for my newbie family members. Thank you for your support btw.

**Comment by DavidNavalho** [comment]
+1 for Scenario 1. As mentioned already, as long as older versions are available for downloading. The tool is really stable anyways, don't see any issue dropping support for these older versions.

**Comment by newmarcel** [comment]
Thanks everyone, this is reassuring 👍!

I will go ahead and drop support for macOS Yosemite and El Capitan in Version 1.6. This release will also come with optimizations for the upcoming macOS Big Sur (11.0).
