### ISSUE TITLE
Feature request: Quit after duration

### ISSUE THREAD

**Issue by jamesgecko** [newmarcel/KeepingYouAwake#128]
A feature that would pair well with "Activate on Launch" is, "Quit after duration." I try to use [Alfred](https://www.alfredapp.com/) to do as many things as possible. I use it to launch KeepingYouAwake when I'm in meetings, but launching KeepingYouAwake after it's already open and deactivated doesn't do anything. To use Alfred as a control mechanism, I have to use a script to close the app and reopen it. "Quit after duration" would close KeepingYouAwake completely, so I could launch it with Alfred again without worrying about if it's open or not.

**Comment by newmarcel** [comment]
This was a quick win, so I've implemented it as an advanced preference in #133. This will be part of the next release.

Thank you very much for this suggestion!

**Comment by jamesgecko** [comment]
Oh, awesome. Thank you!
