### ISSUE TITLE
It's hard to tell the icons apart if you switch between dark mode and light mode

### ISSUE THREAD

**Issue by jes5199** [newmarcel/KeepingYouAwake#131]
I can't tell at a glance which of these cups mean "activated" and which ones mean "de-activated":
<img width="34" alt="Screen Shot 2019-07-25 at 10 36 40 AM" src="https://user-images.githubusercontent.com/16204/61895749-3ce76280-aec8-11e9-9657-6feff5f856da.png">
<img width="36" alt="Screen Shot 2019-07-25 at 10 37 12 AM" src="https://user-images.githubusercontent.com/16204/61895756-3fe25300-aec8-11e9-94e5-190ed772e666.png">
<img width="36" alt="Screen Shot 2019-07-25 at 10 36 55 AM" src="https://user-images.githubusercontent.com/16204/61895763-4244ad00-aec8-11e9-8333-2d4648e1a05a.png">
<img width="28" alt="Screen Shot 2019-07-25 at 10 37 22 AM" src="https://user-images.githubusercontent.com/16204/61895767-44a70700-aec8-11e9-97fc-6d4b888e1788.png">

Ye olde Caffeine had steam coming out of the full-cup version, I miss that.

**Comment by newmarcel** [comment]
I know that I cannot make everyone happy with my icon choice here, but the app has the ability to replace the set of default icons with your own variants: https://github.com/newmarcel/KeepingYouAwake/wiki/Custom-Icons

I even provide the Sketch file here in the git repository so you can use the existing ones as starting point: `Extras/KeepingYouAwake Icons.sketch`

While I won't change the look of the icons at the moment I nevertheless thank you for your feedback 👍
