### ISSUE TITLE
Can't use keepingYouAwake after reboot

### ISSUE THREAD

**Issue by huoleihu** [newmarcel/KeepingYouAwake#134]
MacBook Pro Version:Mid-2014

Using MBP battery power supply, set K-Y-A to start with the computer.
Step
1.Cover the lid.
2.Connect the external screen,the screen doesn't respond.
3.Unplug the external screen cable, open the computer cover,connect the external screen,then cover it.normal screen display

**Comment by newmarcel** [comment]
Closed because of the age of the issue. Maybe this was a problem with an older macOS version.
