### ISSUE TITLE
Allow display to sleep whilst staying awake

### ISSUE THREAD

**Issue by ahydronous** [newmarcel/KeepingYouAwake#138]
@newmarcel
As per https://github.com/newmarcel/KeepingYouAwake/issues/115, https://github.com/newmarcel/KeepingYouAwake/issues/12 and https://github.com/newmarcel/KeepingYouAwake/issues/25
Would it be possible to integrate your commit https://github.com/newmarcel/KeepingYouAwake/commit/4b0e1688344ba61a8e05802891a2599b9be4f614 into 1.5.2 and allow the display to sleep but the Macbook to stay awake?

As long as caffeinate -i (which prevents Macbook sleep in any situation but allows display sleep) is used and not caffeinate -s (which prevents Macbook sleep only on charger whilst allowing display sleep) there should be no buggines/unexpected behaviour (re: https://github.com/newmarcel/KeepingYouAwake/issues/58 and https://github.com/newmarcel/KeepingYouAwake/issues/67) :)

**Comment by creamelectricart** [comment]
Came here just to ask the same thing - this option would be invaluable to us!

**Comment by rbeier** [comment]
+1

**Comment by dotpyfe** [comment]
I was wondering if there had been any movement on this, or plans to include in a 1.5.2 (pre)release?

**Comment by newmarcel** [comment]
I just published version 1.5.2 with this feature 😃 https://github.com/newmarcel/KeepingYouAwake/releases/tag/1.5.2

Enjoy, and thanks everyone for pushing for this feature forward 👍
