### ISSUE TITLE
Right click menu bar icon does not work in Catalina

### ISSUE THREAD

**Issue by ngocphamm** [newmarcel/KeepingYouAwake#139]
As title, I cannot open the context menu with right click on the icon in menu bar. Left click still works normally.

macOS: 10.15.1
KeepingYouAwake was installed using `brew cask`. I also tried getting the app directly from this github repo but there's no luck.

The weird thing is the right click menu still works on another machine of mine, which also has Catalina 10.15.1. The only difference between the 2 machines is the other one (the working one) was upgraded from Mojave, while this one (not working one) has Catalina installed by default.

If there's some debugging needed, please let me know.

Thanks!

**Comment by ngocphamm** [comment]
I found out that this seems to happen only when I have external monitors connected to the mac. Still very weird that

New mac: **HAS right click issue**
* 2 monitors connected to a CalDigit dock (1 USB-C to Display Port, 1 Display Port to Display Port). The dock is connected to the mac with Thunderbolt cable.
* I don't notice any other display issues

Old mac: **DOES NOT have right click issue**
* 1 monitor connected, via HDMI to HDMI cable.

**Comment by reece-bennett** [comment]
Also having this issue, also only happens when connected to an external display.

Running on MacBook Pro 2017. Worked fine on Mojave, upgraded to Catalina 10.15.2 recently and noticed the right click stops working with an external display (connected through USB-C dongle to HDMI cable).

**Comment by ngocphamm** [comment]
So I contacted Bartender app, which have similar/same behavior/issue. They said that it's a bug in Catalina (no surprise??) and they had a workaround but still testing the patch. It was almost a month ago so I'm not sure if they find the workaround stable enough yet.

The issue is with external monitor being "stacked" vertically with the laptop screen, which is what my setup looks like. 
<img width="407" alt="2020-01-13 at 2 33 PM" src="https://user-images.githubusercontent.com/395123/72285707-ac394600-3611-11ea-9ceb-e724a5eeab90.png">

For KeepingYouAwake app, I honestly do not expect the developer(s) to invest their time into this because it's still functional outside of this setup, and also a free app. I wish I had knowledge on mac app development to maybe investigate this myself.

Thanks guys for making this app! We appreciate all your effort making the app, and keeping it free!

**Comment by reece-bennett** [comment]
Yeah I assumed it would be something with Catalina rather than the app. 

Thanks for sharing the vertical stacked info, explains why the issue goes away when I disconnect the external monitor as I also have my external display above the laptop.

**Comment by karangale** [comment]
For now, we can at use the right click menu on icons available on both external displays.
