### ISSUE TITLE
Add possibility to activate KYA with a shortcut

### ISSUE THREAD

**Issue by hattorihanzo9969** [newmarcel/KeepingYouAwake#14]
Hello newmarcel, 

first of all, thank you very much for your work on this beautiful little tool!
Is it possible that you add a feature to (de-)activate KeepingYouAwake with a shortcut?

Best regards!
hattorihanzo9969

**Comment by newmarcel** [comment]
That's a pretty nice idea!

I'll have to do some research how I can define global shortcuts under OS X, but I definitely add it to the roadmap.


Greetings,
Marcel

**Comment by ezig** [comment]
I've defined global shortcuts in the past using Carbon, and it isn't too difficult. The only problem with Carbon is that it's only easy to do with a pre-set shortcut, so we'd have to decide on a key combination and it wouldn't be customizable. 

Adding customizable shortcuts is a bit more more complicated and I've never tried to do it from scratch, but there are good frameworks (I've used [https://github.com/Kentzo/ShortcutRecorder](https://github.com/Kentzo/ShortcutRecorder)) that have shortcut-recording UI elements. There'd probably have to be a new menu item that opened a small window with the shorcut-recorder. 

In either case, if there's still interest in this, I'd be happy to pick it up and add in the feature!

**Comment by newmarcel** [comment]
Sorry for the delayed response, @ezig . My knowledge of the Carbon APIs is pretty limited and I usually prefer the Cocoa way of doing things if possible. But in general I'm open for solutions to this problem and feedback and code is very welcome :smile: 

Just don't start with any UI implementation, as I decided to start working on a preferences window for the next version of *KeepingYouAwake*, which might be the ideal place for such an option.

**Comment by newmarcel** [comment]
Closed and moved to the [Wiki](https://github.com/newmarcel/KeepingYouAwake/wiki/Roadmap).
