### ISSUE TITLE
Menu bar icon needs refresh

### ISSUE THREAD

**Issue by MichaelBuss** [newmarcel/KeepingYouAwake#140]
Usually when you pour a nice cup of coffee it is the content of the cup that changes, not the cup itself. Every time I have recommended this app to friends they have had difficulty telling if it is active or not.
So I have made new icons, hope you like them:

![Example](https://user-images.githubusercontent.com/9961189/70870301-d9062900-1f91-11ea-8632-dbf054565850.png)

[Active.pdf](https://github.com/newmarcel/KeepingYouAwake/files/3965528/Active.pdf)
![Active@1x](https://user-images.githubusercontent.com/9961189/70870114-c8ed4a00-1f8f-11ea-80b3-d24cf7b0421a.png)
![Active@2x](https://user-images.githubusercontent.com/9961189/70870115-c985e080-1f8f-11ea-9941-60941e6dd325.png)
[Inactive.pdf](https://github.com/newmarcel/KeepingYouAwake/files/3965529/Inactive.pdf)
![Inactive@1x](https://user-images.githubusercontent.com/9961189/70870116-c985e080-1f8f-11ea-9645-f508652c592f.png)
![Inactive@2x](https://user-images.githubusercontent.com/9961189/70870117-c985e080-1f8f-11ea-8b1b-87e2ca7aa4f3.png)

If you like them better without the lines in the coffee, or need them for non-retina screens, here's a version without:
[Active_NoLines.pdf](https://github.com/newmarcel/KeepingYouAwake/files/3965531/Active_NoLines.pdf)
![Active_NoLines@1x](https://user-images.githubusercontent.com/9961189/70870149-0c47b880-1f90-11ea-9483-12c812e6041e.png)
![Active_NoLines@2x](https://user-images.githubusercontent.com/9961189/70870150-0ce04f00-1f90-11ea-99bd-ff9c82184e7b.png)

I think they look pretty good in both the light and dark version and the filled body (as opposed to an outline) makes them feel more at home along the other icons on the menu bar.

Am not able to build the app because it can't find sparke.h or something, so can't add them myself, sorry. 🤷‍♂

**Comment by alexandreleroux** [comment]
Nice job @MichaelBuss ! I'm not one of the devs, but I'm +1 for these new menu bar icons. Maybe they could be provided as an 'option' alongside the current 'classic' KYA menu bar icons? We'll see what @newmarcel says :-)

**Comment by prayoholic** [comment]
I wholeheartedly agree.

**Comment by newmarcel** [comment]
I know the current selection of menubar icons doesn't match everyone's taste, but I currently have no plans to replace them.

That's certainly a nice set of icons you created 👍. Did you know there is a way to use custom menu bar icons already? It's documented [here in the wiki](https://github.com/newmarcel/KeepingYouAwake/wiki/Custom-Icons).

**Comment by MichaelBuss** [comment]
That's fair, and thx. Tried finding the icon and replace it as documented, but the path does not contain any icons, unfortunately. 🙁

**Comment by MichaelBuss** [comment]
Thanks. 🙏 I'll try that.
