### ISSUE TITLE
Russian translate

### ISSUE THREAD

**Issue by Kromsator** [newmarcel/KeepingYouAwake#147]
I have translated your KeepingYouAwake program into Russian. The translation is complete. The localization files are included.
[ru.lproj.zip](https://github.com/newmarcel/KeepingYouAwake/files/4056858/ru.lproj.zip)

With respect Alexey Zhdanov

**Comment by newmarcel** [comment]
I've created a pull request to include your translation in the next release 1.6: https://github.com/newmarcel/KeepingYouAwake/pull/155

How do you like to be credited in the About screen? (it's the `Credits.rtf` file)?

It will look like:

```
Russian Translation
Your preferred name/alias <An email address or URL>
```

Thank you very much for your effort 👍

**Comment by Kromsator** [comment]
You can do this: Alexey Zhdanov jdanov1975@icloud.com

**Comment by Kromsator** [comment]
Russian Translation
Alexey Zhdanov <jdanov1975@icloud.com>

**Comment by Kromsator** [comment]
Alexey Zhdanov jdanov1975@mail.ru
