### ISSUE TITLE
Hang on launch for ~1 minute

### ISSUE THREAD

**Issue by registered99** [newmarcel/KeepingYouAwake#15]
After around a minute or so of hanging, the application will become responsive. 

In console, is this log: 

> 4/1/15 20:37:17.349 KeepingYouAwake[25023]: Unbalanced call to enableRelaunchOnLogin:  enableRelaunchOnLogin was called without a preceding call to disableRelaunchOnLogin

I am using the latest stable v1.2. 

Thanks!

**Comment by newmarcel** [comment]
Thanks für reporting! I removed the affected line from the source code and will test it for a while. This "fix" will ship with the next stable update (should be 1.2.1).

Please reopen the issue if this still persists in the next version.

**Comment by registered99** [comment]
I went home, and confirmed the fix. 

It's to remove the check to `if(itemURL)` in NSApplication+LoginItem. 

It did not cause issues for me when there was NULL or dead-linked Login Items.
