### ISSUE TITLE
FR: Better icons

### ISSUE THREAD

**Issue by specter78** [newmarcel/KeepingYouAwake#153]
I have attached images comparing this app with Theine. 

I find theine images to be more clear.

Plus, theine retains the setting from last exit. In this app, even if the app was activated when quit, it starts in deactivated state.

<img width="69" alt="Off" src="https://user-images.githubusercontent.com/40606342/86531221-0dfdad00-bedd-11ea-92a6-0d59f0d5eb8e.png">

<img width="69" alt="On" src="https://user-images.githubusercontent.com/40606342/86531218-0b02bc80-bedd-11ea-92bf-1455218be839.png">

**Comment by newmarcel** [comment]
Hi 👋,
I don't plan changing the menu bar icons in the near future, but you can always use custom icons as described in the wiki, if the default selection doesn't match your needs: https://github.com/newmarcel/KeepingYouAwake/wiki/Custom-Icons

Nevertheless thanks for the feedback and your additional feature suggestion.
