### ISSUE TITLE
Feature Request: 8hr duration

### ISSUE THREAD

**Issue by OldhamMade** [newmarcel/KeepingYouAwake#159]
It's a small thing, but having an 8hr duration that fits with the work day would be great!

**Comment by newmarcel** [comment]
You can actually add an 8 hours duration already by opening `Preferences…` and then selecting `Activation Durations`. With the `+` icon in the bottom right you can add this custom duration to the list.

I hope this is what you are looking for 😺.

**Comment by OldhamMade** [comment]
Sorry, yep, that's perfect! Thanks!
