### ISSUE TITLE
Can KYA be controlled from a script?

### ISSUE THREAD

**Issue by KyleKing** [newmarcel/KeepingYouAwake#16]
Is there a way run KYA for a set time from a script? Or are there plans to develop one? 

I found that if the setting, "Activate on Launch" is checked, you can essentially control KYA like this:
```osascript
# if appplication running, quit KYA. Wait a moment to fully close. Then regardless of status, open the now "closed" app using the setting,  "Activate on Launch" to activate KYA upon launch

tell application "KeepingYouAwake"
	if it is running then
		quit
		set status to "reactivated."
	else
		set status to "activated."
	end if
	
	delay 0.01 # allow KYA to close, don't blink!
	launch # always launch
	
	set output to "KeepingYouAwake has been " & status
	
	return output
	
end tell
```
Then with a cron task, a second script could be run to deactivate KYA at a set time interval:
```osascript
tell application "KeepingYouAwake"
	quit
end tell
```

I would really like something like [Focus'](https://heyfocus.com/) built in cli support:
```
open focus://focus?minutes=25
```

**Comment by newmarcel** [comment]
Cool! I didn't think about scripting support at all until now.

Thanks for sharing your script! :+1: 

I absolutely love the idea of adding a custom URI scheme to control KYA through the command line. I will experiment a bit with the APIs and will post an update here, when I'm ready.

Greetings,
Marcel

**Comment by KyleKing** [comment]
Great!! You're welcome. Unfortunately I'm now having trouble quiting KYA from the script, so this trick isn't working. I think it might be related to the crashes when I tried to deactivate "Start at Login"

If there is anything I can do to help, let me know. I've never built native apps before but I can help reseaerch and bug test

**Comment by newmarcel** [comment]
I had some time to look at the apple events API and I think I can deliver a nice URL-based API pretty easily, e.g.:

    open keepingyouawake:///activate            # indefinitely
    open keepingyouawake:///activate?seconds=5
    open keepingyouawake:///activate?minutes=5
    open keepingyouawake:///activate?hours=5
    open keepingyouawake:///deactivate

- /activate has no effect when already activated
- /deactivate has no effect when already deactivated
- there is a minimum duration of 1 second and a maximum of 12 hours *(arbitrary)*

What do you think… is this enough for a start?

**Comment by KyleKing** [comment]
That sounds awesome! The only other thing I could think of is to fetch the current time left for creating a notification if you're using KYA as a productivity timer or want to get an alert at a certain point. It could be like ```open keepingyouawake:///?``` would return the time left in second (i.e. 3632)
I would love to test those commands out if you have it in the next beta release!

**Comment by newmarcel** [comment]
Sorry for the slow response times recently… I'm back in action :smiley:

[Here](https://github.com/newmarcel/KeepingYouAwake/releases/tag/1.2.2beta1) is the first beta of the scripting update *(v.1.2.2beta1)* Feel free to test-drive this version!

Thanks again @KyleKing for bringing scriptability to my awareness :+1:

**Comment by KyleKing** [comment]
Thanks @newmarcel, the update is awesome and works really well!!]
I've been using the scripting feature for about a week and connected it to Alfred through this workflow if anyone is interested: http://www.packal.org/workflow/activate-keeping-you-awake

**Comment by KyleKing** [comment]
Using the script is so much better! My battery life has even improved
