### ISSUE TITLE
Custom durations & settings lost after restart

### ISSUE THREAD

**Issue by OldhamMade** [newmarcel/KeepingYouAwake#163]
I've found that rebooting my machine (Big Sur) causes the settings to be lost. Custom durations are no longer showing, and the "Start at Login" button is unchecked, despite the app starting at login.

I'm using 1.6.0 via homebrew.

**Comment by newmarcel** [comment]
Sounds like something went wrong with the preferences file. This should never happen and is sadly system behavior and out-of-reach of the app itself.

Can you please try if the following steps solve this problem?
- quit KeepingYouAwake
- open the Finder, open the `Go to` Menu and select `Go to folder…`.
- type in `~/Library/Containers/` and hit `Open`
- look for a `KeepingYouAwake` or `info.marcel-dierkes.KeepingYouAwake` folder and throw it into the trash
- restart `KeepingYouAwake` and apply your settings, toggle the launch at login checkbox a couple of times to make sure the app is properly re-registered to launch at login
- reboot and check if the problem still occurs

Hopefully this solves the problem.

**Comment by OldhamMade** [comment]
Thanks. I've run through the steps (without the reboot as of yet). Since there's not much you can do from the app, I'll close this ticket. Might be good to have these steps in the README or a troubleshooting file.

**Comment by OldhamMade** [comment]
Unfortunately, the issue persists after running through the process and doing a restart.

**Comment by newmarcel** [comment]
I have no clue what might be causing this. I'm closing it again for now. If this re-appears please also list any unusual configuration that your Mac might have… e.g. if you are enrolled in MDM, if your user account is not an admin account of even if you have multiple user accounts.
