### ISSUE TITLE
Start at Login Problems macOS version 11.3 on M1

### ISSUE THREAD

**Issue by alehofde** [newmarcel/KeepingYouAwake#168]
Hi,

after upgrading my Mac M1 to macOS version 11.3 the autostart of the app is no longer working.
Is this an individual issue only with me?

Thanks for double checking

Ps. the helper process is running
-	78	info.marcel-dierkes.KeepingYouAwake.Launcher
1724	0	application.info.marcel-dierkes.KeepingYouAwake.462226.462232

Regards,
alehof

**Comment by savery-endpoint** [comment]
I believe I have also experienced this issue, on 11.4/11.5, on intel platforms.

**Comment by alehofde** [comment]
Issue is solved. Not sure if it is due to the macOS update or due the app update.
