### ISSUE TITLE
Is there a way to automatically make the coffee cup full?

### ISSUE THREAD

**Issue by retpoline** [newmarcel/KeepingYouAwake#170]
First, thanks for the awesome project!

I'm installing this over SSH, so I need a way to make it activate automatically when the app is executed. Can this happen with command line args or a config file, or otherwise?

@newmarcel 

Thanks!

**Comment by newmarcel** [comment]
Hi, great question!

_1st Approach:_ You could use the URI schemes introduced in 1.3, here is the section in the changelog:

https://github.com/newmarcel/KeepingYouAwake/blob/main/CHANGELOG.md#v13

Basically using `open keepingyouawake:///activate` will initially activate the app over SSH. This won't persist after termination.

_2nd Approach:_ If you are looking for a permanent  solution, you can set the "Activate on Launch" checkbox by executing this defaults command before launching the app.

```
defaults write info.marcel-dierkes.KeepingYouAwake info.marcel-dierkes.KeepingYouAwake.ActivateOnLaunch -bool YES
```

**Comment by retpoline** [comment]
You're awesome! Good to know there's two methods, works like a charm.

Thanks!
