### ISSUE TITLE
About-Window in front

### ISSUE THREAD

**Issue by whoinoi** [newmarcel/KeepingYouAwake#18]
Don't know if anybody already mentioned it, but if you right-click on the KeepingYouAwake-icon in the menu bar and choose "About", while you have several other programs opened, you won't see the About-Screen.
You need to close the windows or look in Mission Control for this little About-Window. Perhaps it would be softer, if the About-Windows would be on top of all windows that are currently opened.
Not a big thing but I thought it would be better if someone mentioned it...

**Comment by cleverer** [comment]
This very easy to address, you just have to add this action:
```
- (@IBAction) showAboutDialog:(id)sender {
	[NSApp activateIgnoringOtherApps:YES];
	[NSApp orderFrontStandardAboutPanel:sender];
}
```
in the AppDelegate or somewhere else and connect the action of the "About KeepingYouAwake" menu item to it.

**Comment by newmarcel** [comment]
Thanks @cleverer for the tip! That works great! I guess I should read a bit more about how Cocoa handles windows :sweat_smile:
