### ISSUE TITLE
Option "Indefinitely" cannot be deleted in Settings.

### ISSUE THREAD

**Issue by PieterDePauw** [newmarcel/KeepingYouAwake#188]
Hi all,

It is not possible to remove the duration option "Indefinitely" in the settings, like the other (definite) durations. However, this behaviour could be expected by the user based on the UI. 

Perhaps this preference would be better represented with a checkbox?

**Comment by newmarcel** [comment]
Hi! This is fully intentional. The Indefinitely duration cannot be deleted and will always be there. It's listed in preferences so it can be made the default duration.

I see what you mean… the Delete button is also enabled for entry although it does not work. That's something I can fix.

**Comment by PieterDePauw** [comment]
> Hi! This is fully intentional. The Indefinitely duration cannot be deleted and will always be there. It's listed in preferences so it can be made the default duration.
> 
> I see what you mean… the Delete button is also enabled for entry although it does not work. That's something I can fix.

I am not sure if I actually have made my point clear: my suggestion was twofold. 

_1. UI Design:_ 
De-activating the 'Delete' button for the option "Indefinitely" would indeed fix this issue.

_2. Menu bar options:_ 
The possibility to hide the option "Indefinitely" could be an improvement for users with OLED monitors that might suffer from screen burn-in. Perhaps adding a toggle to control the visibility of options might be a more desirable option?

**Comment by newmarcel** [comment]
Closed. `Indefinitely` will always be available while other durations can be removed, which is by design.
