### ISSUE TITLE
Activate URI schemes doesn't work anymore

### ISSUE THREAD

**Issue by tarunbhardwaj** [newmarcel/KeepingYouAwake#193]
Thank you for this super handy app!

Since version 1.6.3 activate URI scheme is not working anymore on Mac OS 12.2

Both `open keepingyouawake:///activate` and `open keepingyouawake:///deactivate` URIs are just doing deactivation.

**Comment by chadhs** [comment]
@newmarcel just tried your release candidate and it worked great for me.

**Comment by newmarcel** [comment]
Thank you very much @chadhs . I have released this exact version as the official 1.6.4. There is no need to update if you downloaded the above zip file.

Hopefully this resolves the issue for everyone.

**Comment by chadhs** [comment]
rock on; thank you for your work on this!

**Comment by tarunbhardwaj** [comment]
Working as expected now, Thanks
