### ISSUE TITLE
Doesn't work on OSX Ventura

### ISSUE THREAD

**Issue by marimeireles** [newmarcel/KeepingYouAwake#194]
The app install without problems. When I try to run it, it just doesn't do anything, doesn't open also doesn't crash.
I'm using the M1.
Happy to provide more context given some info on how to provide logs here.
Thanks for the amazing work this app is ⭐️!

**Comment by marimeireles** [comment]
It was also automatically uninstalled as a few other apps I had once I updated it.
Cheers folks!

**Comment by marimeireles** [comment]
The app doesn't even start for me.

**Comment by marimeireles** [comment]
Ahhh okay
Sorry, I was confused.
Ahn, yeah. Thank you!
Let me know if I can help to debug it. I have no clue about objective c but happy to generate logs 😅

**Comment by newmarcel** [comment]
The app is in general fully M1/M2 and Ventura compatible. Here are a couple of questions to track down any problems:

- where is the app installed? (should be the `/Applications` folder)
- while it's running and you notice that your Mac still falls asleep:
  - open `Activity Monitor` from the `/Applications/Utilities` folder or by using Spotlight
  - enter `caffeinate` into the search bar in the top left, there should be exactly one entry
  - when you deactivate KYA the `caffeinate` entry should disappear
- please paste the output of the `pmset -g` command when you notice any problems (you can type this into the `Terminal` app from the `/Applications/Utilities` folder or by using Spotlight)

Thanks 🙂

**Comment by marimeireles** [comment]
It's installed under `/Applications`
I `open` the app
- When I open the activity monitor and search for caffeinate nothing shows up
- If I try to uninstall the software osx says it's in use
- When I open `htop` and search for keepinyoueawake it shows up
I killed it, uninstalled, installed again. Same problem:
It seems to be running just fine but I have no GUI.
Here's the output:
```
pmset -g
System-wide power settings:
 SleepDisabled		0
Currently in use:
 standby              1
 Sleep On Power Button 1
 hibernatefile        /var/vm/sleepimage
 powernap             1
 networkoversleep     0
 disksleep            10
 sleep                1 (sleep prevented by powerd, coreaudiod)
 hibernatemode        3
 ttyskeepawake        1
 displaysleep         0
 tcpkeepalive         1
 lowpowermode         0
 womp                 0
 ```
 Thanks!!

**Comment by newmarcel** [comment]
OK, thanks! This looks like it's running but it's not active. This looks normal so far 👍.

Do you use any tools that manage the macOS menu bar and hide items by default? Can you quit these and check if the icon shows up? The expectation is, when you run KeepingYouAwake it shows up as coffee cup icon in the menu bar at the top of your screen.
Also when there are a lot of status items in the menu bar, macOS sometimes hides them (especially on Macs with a camera notch). If that's the case, can you try quitting some of these apps until (hopefully!!) the KYA icon appears? You can relaunch and reorder them afterwards.

**Comment by marimeireles** [comment]
Okay!
One of these things... Fixed my issue. Maybe I had to reset the computer? But now it works.
Thank you for the feedback!!
I guess I'll close it now as I can't reproduce it.
Cheers and thanks again!

**Comment by amitkot** [comment]
@newmarcel I just had the same behavior of no KeepingYouAwake icon on menu bar. Closing other apps helped.
Is this the best builtin behavior on Ventura? Is there a recommended "menu bar icons manager" you can suggest? 🙏
