### ISSUE TITLE
command line parameters with duration don't seem to work

### ISSUE THREAD

**Issue by subyraman** [newmarcel/KeepingYouAwake#195]
Heya! The changelog [here](https://github.com/newmarcel/KeepingYouAwake/blob/main/CHANGELOG.md#v13) suggests we should be specify a custom sleep timer duration from the command line, like `open keepingyouawake:///activate?seconds=5`.

However, in version 1.6.4 this seems to not work. 

```
➜  ~ open keepingyouawake:///activate?seconds=5
zsh: no matches found: keepingyouawake:///activate?seconds=5
```

Any thoughts about why that is? `activate` and `deactivate` work without parameters.

**Comment by newmarcel** [comment]
Ah ok, `zsh` doesn't like unquoted URLs. Can you try adding `"` around the URL after the `open` command? I think `bash` was a bit more tolerant with these.

e.g.  `open "keepingyouawake:///activate?seconds=5"`

**Comment by subyraman** [comment]
Oh goodness you're correct. Thanks so much!
