### ISSUE TITLE
External display advanced option spams caffeinate processes

### ISSUE THREAD

**Issue by mxsrm** [newmarcel/KeepingYouAwake#203]
Screenshot attached. When using the "Advanced" option to activate when an external display is connected this is what my system looks like after using an external display for about an hour. Disabling KYW does not close those processes, you have to manually kill them.

When the option is disabled and KYA is on, only one process exists.

<img width="1221" alt="Screenshot 2023-05-21 at 13 57 30" src="https://github.com/newmarcel/KeepingYouAwake/assets/7951225/d9c5d78f-684d-490a-8f81-6104fd56477d">

KYA Version 1.6.4 (1060400) on a MBP with M2 processor running macOS Ventura 13.4.

**Comment by newmarcel** [comment]
This is indeed a nasty bug. I can reproduce this (even with an iPad connected as sidecar display) and will start working on it. This bug slipped through because I'm not usually working with external displays, so I did not notice it. Thanks for reporting this!

**Comment by mrkukov** [comment]
I hope this could be fixed since it would be perfect "trigger" for my usecase but the extra processes makes it impossible to use. I hope you get some time to fix it. :)

**Comment by newmarcel** [comment]
A fix for this issue will be part of the next app update.

Sorry, this took so long, I don't usually work with external displays _(as mentioned above)_, so I only just now got to resolving these problems.
