### ISSUE TITLE
Activate when connected to external display doesn’t work for mirroring mode

### ISSUE THREAD

**Issue by pan-long** [newmarcel/KeepingYouAwake#210]
KeepingYouAwake doesn’t activate if the connected display is in mirroring mode (mirroring the built in display)

**Comment by puddleoasis** [comment]
I would benefit from a solution for this!

**Comment by newmarcel** [comment]
Thanks for describing this problem! A fix for this issue will be part of the next app update.

Sorry, this took so long, I don't usually work with external displays, so I only just now got to resolving these problems.

**Comment by pan-long** [comment]
Please don’t say sorry, your contribution to open source project is highly
appreciated!
