### ISSUE TITLE
Downloader differs from previously opened versions

### ISSUE THREAD

**Issue by zorgiepoo** [newmarcel/KeepingYouAwake#214]
Due to a sandboxing issue new to macOS Sonoma and due to this app and other apps using Sparkle's Downloader XPC Service, users may see a one-time system warning dialog when checking for updates about "Downloader" [differs](https://github.com/sparkle-project/Sparkle/issues/2507#issuecomment-1962249064) from previously opened versions.

It looks like KeepingYouAwake wants to use the Sparkle's Downloader XPC Service from following [Sparkle's sandboxing guide](https://sparkle-project.org/documentation/sandboxing/) because the app is not entitled with an outgoing network connection (`com.apple.security.network.client`) entitlement. So there are a couple ways to fix this issue:

* KeepingYouAwake can update to Sparkle 2.6.0 or later (which disables sandboxing for the Downloader XPC Service by default to avoid conflicts) (easiest way)
* KeepingYouAwake can re-compile their current version of Sparkle with a custom `XPC_SERVICE_BUNDLE_ID_PREFIX`
* KeepingYouAwake can enable the outgoing network connection (com.apple.security.network.client) entitlement on its app instead of enabling the Downloader XPC Service as there are other drawbacks with using the downloader service (e.g. Sparkle can't use WebKit 2).

See sparkle-project/Sparkle#2514 and the [updated sandboxing guide](https://sparkle-project.org/documentation/sandboxing/) for more information on the issue.

[edit]: Updated to include 3rd option of not using downloader service.

**Comment by newmarcel** [comment]
Thank you for the report! I will read up on the Sparkle release notes and make sure it's updated to the latest release with the next app update.
