### ISSUE TITLE
README.MD: Link to Lighthead Software “faulty”

### ISSUE THREAD

**Issue by DF3LX** [newmarcel/KeepingYouAwake#215]
Lighthead Software seem to be not any more in charge of the linked domain.
It directs now to some kind of casino (scam).
https://github.com/newmarcel/KeepingYouAwake?tab=readme-ov-file#inspired-by-caffeine
links to:
lightheadsw.com/caffeine/

May be worth removing the link.

Cheers, Felix

**Comment by newmarcel** [comment]
Ah, that's a shame, that the site is gone. Thank you so much for reporting this 👍. I will replace the link with an archived version of their site, which will be safe to visit again.
