### ISSUE TITLE
Icon Hides/Appears When Scrolling Desktops

### ISSUE THREAD

**Issue by FatalEnigma** [newmarcel/KeepingYouAwake#22]
When I change from one desktop to another and watch the icon, it appears to flicker colour or even hide/reappear completely when changing desktops using the gesture while nothing else I have in the menu bar does this.

I know this is a minor UI bug but would be cool to fix this if it is easy.

**Comment by newmarcel** [comment]
I'm closing this issue because I can't reproduce it and haven't received similar reports.
