### ISSUE TITLE
Prevent mac from sleep but allow screen saver?

### ISSUE THREAD

**Issue by FezVrasta** [newmarcel/KeepingYouAwake#25]
I'd like to prevent my Mac from going in sleep mode but I do want to allow my mac to enable the screen saver to prevent problems to my screen.

Caffeine doesn't allow it, what about KYA?

Thanks

PS; Sorry, with screen saver, I mean allowing my screen from turning off.

**Comment by unluisco** [comment]
+1

**Comment by e40** [comment]
+1 as well.  I want the effect of `caffeinate -s`.  If the command line to `caffeinate` could be customized, then we'd all be happy!

**Comment by e40** [comment]
It's not official, but I did this and it's working fine for me:

https://github.com/e40/KeepingYouAwake/commit/dcf7e5ecea18f8e46deb7b17560aa87e100d144e

Of course, I'd love to see the feature in the official version as an option or preference.  This is just to tide me over.

**Comment by jeffbyrnes** [comment]
:+1:

**Comment by alexandreleroux** [comment]
Doesn't this already works? With KYA 1.3.1 enabled, I can launch MacOS X's screensaver from the hot corner and let it go indefinitely. That doesn't work for you? If it does work, then we can close this ticket. Cheers -- Alex

**Comment by FezVrasta** [comment]
I'm talking about the automatic screensaver

**Comment by alexandreleroux** [comment]
Thanks for the precision

**Comment by copumpkin** [comment]
:+1: 

Basically, expose the flexibility that `caffeinate` exposes, or at least let the screen sleep without the computer turning off.

**Comment by newmarcel** [comment]
OK you convinced me :grinning:, I will expose an advanced preference to allow the screen saver to activate `(caffeinate -s)`. :+1: 

I schedule this pref with the upcoming v1.4 release.

This will also solve #12.

Thanks!

**Comment by e40** [comment]
VERY NICE!  Thank you!

**Comment by newmarcel** [comment]
This feature landed in `master`. To test it, checkout and build `master`, go to "Preferences…" > "Advanced"  and check *"Allow the display to sleep"* (and restart the app if needed). This just wraps `caffeinate -s`

**Comment by FezVrasta** [comment]
Thanks :)

**Comment by copumpkin** [comment]
Awesome, thanks!

**Comment by danechitoaie** [comment]
Any idea when new version would be released with this new feature?

**Comment by newmarcel** [comment]
Good question. Since I feel good about the current state of `master` I will start the beta cycle this weekend with 1.4.0beta1. You can then test the new features and report any bugs here.

**Comment by newmarcel** [comment]
Here you go, 1.4.0beta1 is live: https://github.com/newmarcel/KeepingYouAwake/releases/tag/1.4beta1

You can find the toggle in `Preferences…` -> `Advanced` -> `Allow the display to sleep`.

**Comment by e40** [comment]
Works great.  THANK YOU.

**Comment by alexandreleroux** [comment]
This issue should be closed, now that it's part of release 1.4.0, agreed?

**Comment by copumpkin** [comment]
Is `caffeinate -s` really the option we want here? I think what I'm looking for is `-i` without `-d`, which should prevent the computer from sleeping without preventing the displaying from sleeping.

The documentation for `-s` says:

>      -s      Create an assertion to prevent the system from sleeping. This assertion is valid only when system is running on AC power.

Which basically means that when I select the KeepingYouAwake "Allow the display to sleep" mode, my machine will go to sleep when I'm not plugged in. I think `-i` would achieve the desired goal while still keeping my machine awake when not plugged in.

Alternately, could you just expose the underlying command-line options?

**Comment by NeckBeardPrince** [comment]
@copumpkin Okay, I was wondering why the hell my laptop just went to sleep while I had this option selected. Yeah @newmarcel this breaks the app from doing what it should be doing.

**Comment by alokdhir** [comment]
What happened to this? I am on 1.5 and there is no option to 'Allow display to sleep'.

**Comment by creamelectricart** [comment]
As mentioned above by @copumpkin and in issue #138, this should actually be possible using -i with caffinate - any chance of please implementing this @newmarcel ? Allowing the display to automatically sleep would go a long way to help reduce energy usage in our environment. @ @ #138
