### ISSUE TITLE
Crash when deselecting "Start at login"

### ISSUE THREAD

**Issue by inistor** [newmarcel/KeepingYouAwake#26]
KYA is running.
Right click on top menu icon.
Click on "Start at login" (default is disabled)
Right click on top menu icon again.
"Start at login" is now enabled.
Click on "Start at login".
The icon disappears (KYA crash).

OSX Yosemite 10.10.4
MacBook Pro (Retina, 15-inch, Mid 2015)
KYA: Version 1.2.2beta1 (123) 

Update: added KYA version

**Comment by byalextran** [comment]
was just looking through the issues and can confirm this happens with me as well. 

Yosemite 10.10.4
MacBook Pro (Retina, 13-inch, Late 2013)
KYA Version 1.2.1 (122)

**Comment by schmidtbs** [comment]
confirmed

Yosemite 10.10.4
MacBook Pro (Retina, 13-inch, Mid 2014)
KYA Version 1.2.2beta1 (123)
