### ISSUE TITLE
Remove shadow from menu bar icon

### ISSUE THREAD

**Issue by TylerEich** [newmarcel/KeepingYouAwake#28]
This app is awesome. Major improvement over the old Caffeine icon.

That said, the icon would be just a touch cleaner without the shadow, and maybe moved down a pixel or two

Icons | Current | No Shadow
------------ | ------------- | -------------
Inactive | ![inactive-original](https://cloud.githubusercontent.com/assets/3460063/9237198/a38f7a04-4117-11e5-99e1-bb8add0fabe7.png) | ![inactive-no-shadow](https://cloud.githubusercontent.com/assets/3460063/9237208/b79e24d2-4117-11e5-98bc-670be83e767d.png)
Active | ![active-original](https://cloud.githubusercontent.com/assets/3460063/9237197/a37c04a6-4117-11e5-83c7-53cd983861de.png) | ![active-no-shadow](https://cloud.githubusercontent.com/assets/3460063/9237207/b78b73be-4117-11e5-8d52-7081c7dced15.png)

![screen-active-no-shadow](https://cloud.githubusercontent.com/assets/3460063/9237701/95bc841e-411a-11e5-938c-a4958b3d9ab8.png)
![screen-inactive-no-shadow](https://cloud.githubusercontent.com/assets/3460063/9237702/95c3902e-411a-11e5-9a88-b061d192ab47.png)

**Comment by alvarnell** [comment]
Personally, I like it just as it is.

-Al-

**Comment by newmarcel** [comment]
OK, I understand now that people love custom icons, so I started working on it in the `custom-menubar-icons` branch. I will also remove the inactive icon dimming.


This feature will be in the next beta release… but it's not ready yet.

**Comment by mileswd** [comment]
:+1:

**Comment by newmarcel** [comment]
I just released version 1.2.2beta2 with the custom icons support. See the changelog for reference https://github.com/newmarcel/KeepingYouAwake/releases/tag/1.2.2beta2

Have fun with your custom icons 😄!
