### ISSUE TITLE
Awake duration

### ISSUE THREAD

**Issue by emagnier** [newmarcel/KeepingYouAwake#3]
Nice project!

But I would love to have the "Activate for" menu, where I could set the awake duration to:
- 5 minutes 
- 10 minutes
- 15 minutes
- 30 minutes
- 1 hour
- 2 hours
- 5 hours
- Indefinitely

Like Caffeine :)

**Comment by 1aurabrown** [comment]
+1 @fergo79

**Comment by bdkjones** [comment]
+1 for the default duration request. This is the only thing missing from the app in my opinion.

**Comment by Nosrac** [comment]
I submitted a pull request adding this feature: https://github.com/newmarcel/KeepingYouAwake/pull/27

**Comment by newmarcel** [comment]
Thanks to @Nosrac this feature is now in the master branch and will ship with the next release :+1:. Just hold down `option` (`alt`) to set the default duration.

I consider this issue fixed.
