### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by rjaakke** [newmarcel/KeepingYouAwake#31]
Sorry for the newby question but I'm getting errors building the project in Xcode.

KYAEvent.h it doesn't like line 26:
@property (copy, nonatomic, readonly, nullable) NSDictionary<NSString *, id> *arguments;

Since the file hasn't changed for a while I'm assuming it's some setting in my build environment but I have no clue where to look.

**Comment by alvarnell** [comment]
What version are you trying to build?

What version of OS X / XCode are you using?

Why not just download the app instead of building it from source?

**Comment by newmarcel** [comment]
I guess it fails because you are using Xcode 6? The current master branch requires a recent Xcode 7 beta because of the nullability annotations. Sorry for the inconvenience.

**Comment by rjaakke** [comment]
OSX 10.10.5 and Xcode 6.4

I wanted to try the new beta 2 which is not in the releases yet.
Main reason is that I really miss the ability to set default duration to something else then indefinitely in the beta 1

**Comment by rjaakke** [comment]
I don't have Xcode 7 so that explains enough.

**Comment by newmarcel** [comment]
@rjaakke Ok, you can download the current beta form the Apple developer portal. This issue should resolve itself in the coming weeks when Xcode 7 will be released.

I'm also waiting for the final Xcode 7 release to prepare a new beta version… I don't like releasing anything with a beta version of Xcode :smile:
