### ISSUE TITLE
Prevent user from selecting "Indefinitely"

### ISSUE THREAD

**Issue by tincansandtwine** [newmarcel/KeepingYouAwake#32]
Working in an large scale environment, we have to enforce a 15 minute screenlock. Obviously there are scenarios where this wouldn't be ideal, and would like to offer our users KYA as an option, but "indefinitely" can't be an option, as this could lead to just setting it to indefinitely, starting at login, and activating on launch, effectively defeating the security requirement.

We are willing to ask our users to observe the honor system for now, but having the ability to administratively remove the option altogether would make it that much easier.

**Comment by newmarcel** [comment]
I thought about adding this feature to the app, but decided against it. But there is hope :smile: You can always create a fork of KeepingYouAwake here on GitHub and remove the "indefinitely" option from the forked app.

KYA is MIT-licensed, so you are free to modify the source in any way. You don't have to do it, but it would be nice if you could rename the forked app to avoid any confusion and maybe change the icon.
