### ISSUE TITLE
"Activate for Duration" setting is not memorized

### ISSUE THREAD

**Issue by josephsieh** [newmarcel/KeepingYouAwake#33]
Current version of keeping you awake (1.2.1) does not remember what users set for "Activate for Duration", set for 1 hour for example, if user click the menu icon to disable/enable again, or quit and relaunch.  Current version will just reset the "Activate for Duration" to "Indefinitely" automatically.

It will be the best and convenient for users to be able to "set the default value".

**Comment by newmarcel** [comment]
You can now set the default timer expiration in version 1.2.2beta2. Click on the menu bar icon, navigate to "Activate for duration" and hold down the option key. Now you can set the default expiration time when you click the menu bar icon.
