### ISSUE TITLE
Scheduled (de)activation

### ISSUE THREAD

**Issue by dbkaplun** [newmarcel/KeepingYouAwake#34]
Is it possible to set KeepingYouAwake to work on a schedule? I have a work computer that I like to use KeepingYouAwake on during the day but sometimes I forget to turn it off.. Company got an email from me this morning that I didn't write! Would be so great to be able to set it to automatically turn on at 9AM and off at 6PM!

**Comment by newmarcel** [comment]
That's a nice idea! But the app doesn't support scheduled deactivation at the moment.

Maybe there is way to do this with scripting or automation? Maybe somebody else has an idea how to solve this issue?

**Comment by gagern** [comment]
I guess you could use [`crontab`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/crontab.1.html) to schedule the deactivation. Run `crontab -e` and add this line:

```
0 18 * * 1-5 open keepingyouawake:///deactivate
```

See [crontab(5)](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man5/crontab.5.html#//apple_ref/doc/man/5/crontab) for details about the format.

**Comment by dbkaplun** [comment]
@gagern interesting. Is there a way to activate it at 9AM as well?

**Comment by gagern** [comment]
@dbkaplun Entering the corresponding cron line is easy, but I'm not sure what would happen if your computer were actually sleeping at 9AM. To my knowledge cron does not catch up on missed tasks, nor will it cause the computer to wake up from sleep. So things there would be more tricky.

**Comment by dbkaplun** [comment]
That makes sense. In that case I would only want to activate it if I've already turned the computer on. I assume the corresponding line would look something like this:
```
0 9 * * 1-5 open keepingyouawake:///activate
```

Anyway, closing this issue as it is resolved. Thanks!

**Comment by gagern** [comment]
Yes, `keepingyouawake:///activate` is the URL listed in the [1.3 release description](https://github.com/newmarcel/KeepingYouAwake/releases/tag/1.3). Should be mentioned in the README, too, I think.
