### ISSUE TITLE
icon design drafts

### ISSUE THREAD

**Issue by tiiiecherle** [newmarcel/KeepingYouAwake#35]
Hey,

first of all I really like the app and I use it every day. Thanks for your work. Like a few other users I decided that I want another icon and I did 10 different iconsets that are really close to the old one. Some have only minor changes in the size of the outline. I personally like number 9 and number 5 best.

As uploading a zip with all the data is not supported please let me know how to hand you over the files including the illustrator source file.

I will also try to submit a pull request with the one I´m using right now (number 9). As I´ve never done that I don`t know if this is going to work.

It would be nice to see this included and if you could build a new release soon.

Thanks in advance for this very nice project and I hope you`ll find some time to update it on regular basis.

Kind regards,

Tom

iconset 1
![active](https://cloud.githubusercontent.com/assets/7059936/10561110/8c4e3e4e-751e-11e5-9c32-9e9d7535b33d.png)
![active 2x](https://cloud.githubusercontent.com/assets/7059936/10561111/8c7b4948-751e-11e5-96bf-a9e28e0906fd.png)
![inactive](https://cloud.githubusercontent.com/assets/7059936/10561113/8c82da8c-751e-11e5-9f31-97443a5e0d9d.png)
![inactive 2x](https://cloud.githubusercontent.com/assets/7059936/10561112/8c7e8770-751e-11e5-9fea-367826810bc6.png)

iconset 2
![active](https://cloud.githubusercontent.com/assets/7059936/10561107/83fdecd0-751e-11e5-8fe1-49741879b2b5.png)
![active 2x](https://cloud.githubusercontent.com/assets/7059936/10561109/83ff9f94-751e-11e5-9af6-c4f61e49bdc8.png)
![inactive](https://cloud.githubusercontent.com/assets/7059936/10561106/83fccefe-751e-11e5-9f11-ae5ae2a7d2de.png)
![inactive 2x](https://cloud.githubusercontent.com/assets/7059936/10561108/83fe1232-751e-11e5-85a9-bc7c3748ce3a.png)

iconset 3
![active](https://cloud.githubusercontent.com/assets/7059936/10561101/7981b494-751e-11e5-9d99-328edc92254d.png)
![active 2x](https://cloud.githubusercontent.com/assets/7059936/10561103/79b7db32-751e-11e5-900e-23cfe0f798c8.png)
![inactive](https://cloud.githubusercontent.com/assets/7059936/10561102/79b46e0c-751e-11e5-8685-d97bb2b3a9c2.png)
![inactive 2x](https://cloud.githubusercontent.com/assets/7059936/10561104/79b7e2e4-751e-11e5-88db-2e91936f0db5.png)

iconset 4
![active](https://cloud.githubusercontent.com/assets/7059936/10561097/6d276a18-751e-11e5-8edf-3231f4bbeee8.png)
![active 2x](https://cloud.githubusercontent.com/assets/7059936/10561099/6d27d322-751e-11e5-8a3c-25f27405b015.png)
![inactive](https://cloud.githubusercontent.com/assets/7059936/10561100/6d2961ba-751e-11e5-9bd9-3500701ec72d.png)
![inactive 2x](https://cloud.githubusercontent.com/assets/7059936/10561098/6d277e40-751e-11e5-91bc-4662abf9dd4a.png)

iconset 5
![active](https://cloud.githubusercontent.com/assets/7059936/10561090/6450d0fa-751e-11e5-81a8-1d9684948c4a.png)
![active 2x](https://cloud.githubusercontent.com/assets/7059936/10561091/647f3396-751e-11e5-9082-a2d338b7dce9.png)
![inactive](https://cloud.githubusercontent.com/assets/7059936/10561092/648a1ba8-751e-11e5-9d73-05aa39f8660e.png)
![inactive 2x](https://cloud.githubusercontent.com/assets/7059936/10561093/648a9254-751e-11e5-95e6-20c2ccb22d8e.png)

iconset 6
![active](https://cloud.githubusercontent.com/assets/7059936/10561087/56d6144e-751e-11e5-8a8f-860758ef4535.png)
![active 2x](https://cloud.githubusercontent.com/assets/7059936/10561089/56d84656-751e-11e5-83ba-28b4d8462688.png)
![inactive](https://cloud.githubusercontent.com/assets/7059936/10561086/56d60742-751e-11e5-9067-e2be176bda44.png)
![inactive 2x](https://cloud.githubusercontent.com/assets/7059936/10561088/56d6d3a2-751e-11e5-87e1-f7fe27c4544c.png)

iconset 7
![active](https://cloud.githubusercontent.com/assets/7059936/10561082/4c41fb06-751e-11e5-8ef6-c54f6731184e.png)
![active 2x](https://cloud.githubusercontent.com/assets/7059936/10561083/4c7101c6-751e-11e5-89c9-fec146378b72.png)
![inactive](https://cloud.githubusercontent.com/assets/7059936/10561084/4c73b146-751e-11e5-85c6-3c1b17af7dd4.png)
![inactive 2x](https://cloud.githubusercontent.com/assets/7059936/10561085/4c75c710-751e-11e5-9c65-1c7ce64b9d0d.png)

iconset 8
![active](https://cloud.githubusercontent.com/assets/7059936/10561073/4079a12a-751e-11e5-9122-9ed3e21847cb.png)
![active 2x](https://cloud.githubusercontent.com/assets/7059936/10561071/40773ebc-751e-11e5-82f3-21605091f86d.png)
![inactive](https://cloud.githubusercontent.com/assets/7059936/10561072/40797b78-751e-11e5-8990-1a4a4e905b4b.png)
![inactive 2x](https://cloud.githubusercontent.com/assets/7059936/10561074/407a43d2-751e-11e5-8c1e-f027634bab76.png)

iconset 9
![active](https://cloud.githubusercontent.com/assets/7059936/10561067/35e834d8-751e-11e5-9581-b56ecb833cf4.png)
![active 2x](https://cloud.githubusercontent.com/assets/7059936/10561066/35e74f5a-751e-11e5-8933-18bde6c3a345.png)
![inactive](https://cloud.githubusercontent.com/assets/7059936/10561069/35eba578-751e-11e5-9fde-a9c29bb3238b.png)
![inactive 2x](https://cloud.githubusercontent.com/assets/7059936/10561068/35e8efea-751e-11e5-918e-46376a500fae.png)

iconset 10
![active](https://cloud.githubusercontent.com/assets/7059936/10561062/2683cb74-751e-11e5-9ee4-3e0423cdaf25.png)
![active 2x](https://cloud.githubusercontent.com/assets/7059936/10561064/26b489da-751e-11e5-9a04-df9a73e8e2c6.png)
![inactive](https://cloud.githubusercontent.com/assets/7059936/10561065/26bf78d6-751e-11e5-94df-c313117570c3.png)
![inactive 2x](https://cloud.githubusercontent.com/assets/7059936/10561063/26b31a00-751e-11e5-97ce-1a3a59c29236.png)

**Comment by tiiiecherle** [comment]
hey again,

I managed the pull request and uploaded all icon sets including the illustrator file and a testbuild of every icon (all with version 1.2.2beta2) to my fork:

https://github.com/tiiiecherle/KeepingYouAwake/tree/master/keepingyouawake_icons

Hope this helps.

Kind regards,



Tom

**Comment by newmarcel** [comment]
Hey thanks for taking the time and creating all those alternative icons :+1:  I just released the second and final beta for 1.2.2 where you can use alternative icons as described here: https://github.com/newmarcel/KeepingYouAwake/releases/tag/1.2.2beta2

There is no need anymore to modify the main app to have custom icons. Therefore I won't accept your pull request, because I don't want to change the current set of icons. Users are now free to choose any icons they like!

**Comment by tiiiecherle** [comment]
thanks, will try it out now ;)

**Comment by tiiiecherle** [comment]
Hey, working nicely, thanks a lot.

Perhaps you can add something like an icon collection repository for the user to have a choice in advance as not every user does his or her own icons. You can add yours and mine for the beginning ;)

**Comment by newmarcel** [comment]
Good idea, but I don't intend to provide any alternative icons myself.

But I created a wiki page for [Custom Icons](https://github.com/newmarcel/KeepingYouAwake/wiki/Custom-Icons). Feel free to host your icon set here on GitHub and add a new entry to the "Alternative Icons" section in the form of `<Icon Set Name> by <Your Username>`. Thanks! :+1:

**Comment by tiiiecherle** [comment]
Thanks, but I don`t get it completely. Where exactly is the "Alternative Icons" section and how do I add my icons?

**Comment by newmarcel** [comment]
I was referring to the wiki page I created today: https://github.com/newmarcel/KeepingYouAwake/wiki/Custom-Icons

Click **Edit** and paste a link to your hosted icons into the "Alternative Icons" section. I added an example entry so you can see how it is supposed to look like.

**Comment by tiiiecherle** [comment]
ok, thanks.

Where am I supposed to put the files? My idea was to make a directory directly in your github project so that users see it more obviously.

Your idea was to make another github project in my account and link there from your wiki, right?

**Comment by newmarcel** [comment]
Exactly, host them on your GitHub page and add a link to the wiki.

**Comment by tiiiecherle** [comment]
perfect, done ;)

And thanks again for all your effort. I like the tool a lot!
