### ISSUE TITLE
Any chance of releasing the new Beta anytime soon?

### ISSUE THREAD

**Issue by rjaakke** [newmarcel/KeepingYouAwake#37]
Hi Marcel,

The new XCode is available so I was wondering if you will be releasing the new beta anytime soon.
I really miss setting the default values in the current beta.

Thanks in advance.

Robert

**Comment by newmarcel** [comment]
Done. v1.2.2beta2 :grin:

Sometimes life takes precedence and I can't release new versions. But the difficult times are hopefully over and I'm back in action. Expect the final release of 1.2.2 soon!

**Comment by rjaakke** [comment]
Thanks!
