### ISSUE TITLE
I get "Insecure update error!" each time I run the app (that I build)

### ISSUE THREAD

**Issue by e40** [newmarcel/KeepingYouAwake#39]
I want to make minor modifications to the `caffeinate` command (to change it to `-s`) so I'm building my own version of the app.  I don't have a developer account so I turned off code signing, installed Carthage and did the `carthage bootstrap`.  When I run the built app, I get the "Insecure update error!" pop up.

How to make this go away?

Thanks.

**Comment by newmarcel** [comment]
Hi! This might be related to the automatic update check on launch.

Try disabling the automatic update by changing the key `SUEnableAutomaticChecks` in the `Info.plist` to `NO`.

**Comment by e40** [comment]
Tried that.  Still happens.

**Comment by newmarcel** [comment]
This error might be related to the missing app transport security Info.plist settings in version v1.3.0. Can you check it again with the current master (>= 1.3.1)?
