### ISSUE TITLE
Update to Sparkle 1.13.1 or newer

### ISSUE THREAD

**Issue by t3rminus** [newmarcel/KeepingYouAwake#45]
A critical MITM vulnerability has been disclosed in the Sparkle framework: 
http://arstechnica.com/security/2016/02/huge-number-of-mac-apps-vulnerable-to-hijacking-and-a-fix-is-elusive/

A fix has been released as of version 1.13.1. KeepingYouAwake was one of the few apps on my system flagged for using an older version.
https://github.com/sparkle-project/Sparkle/releases/tag/1.13.1

I would be extremely happy to see this resolved quickly.

**Comment by newmarcel** [comment]
I already committed the new Sparkle version in master and 1.4beta1 shipped with Sparkle 1.13.1 as will 1.4.

https://github.com/newmarcel/KeepingYouAwake/commit/aa0265e04709eb74d9832e9f40744b3ce74b9e49

Thanks for reporting, it's a serious issue :+1: 

I'll close this issue when I've shipped a stable release with the updated Sparkle.

**Comment by alvarnell** [comment]
Although the Sparkle.framework version is older, KeepingYouAwake uses https for it’s update, so it’ should not be vulnerable to this issue.

-Al-

**Comment by alvarnell** [comment]
Sorry, I was looking at v1.22b1 which used https, but for whatever reason I see that v1.3.1 did not.  So looks like I need to update to v1.4b1 immediately.

-Al-

**Comment by alexandreleroux** [comment]
I suggest closing this ticket since KYA version 1.4.0 includes Sparkle 1.14.0
