### ISSUE TITLE
Option to set left-click activation duration

### ISSUE THREAD

**Issue by jayqi** [newmarcel/KeepingYouAwake#47]
When you left-click to activate KeepingYouAwake, it always activates Indefinitely. 

Caffeine has the feature where you can set the default activation duration (e.g., 1 hour) for when left-clicking. Any chance we can get this in KeepingYouAwake as well?

**Comment by alexandreleroux** [comment]
This feature has been implemented in KYA version 1.4.0 in the new Preferences pane, I suggest closing this ticket. Thanks -- Alex

**Comment by jayqi** [comment]
Just upgraded to 1.4.0 and see the feature now. Thanks!
