### ISSUE TITLE
KYA usage metrics?

### ISSUE THREAD

**Issue by alexandreleroux** [newmarcel/KeepingYouAwake#49]
Do we have a way to have an estimate of the number of KYA users? Can the "Check for Updates..." be used to get such an estimation? Any other KYA metrics we could have access to? Thanks -- Alex

**Comment by newmarcel** [comment]
Actually, I don't want to deal with any kind of server component or web hosting for this project… I only host the static Sparkle feeds here on GitHub pages, therefore this isn't possible. I only have the GitHub metrics for the project, like visitors, clones and referrers… which can produce interesting results, e.g. I didn't notice that the app was mentioned on [*Mac Power Users* #315](https://www.relay.fm/mpu/315) 😄 

I personally don't want to track anything and I don't want to collect any usage data at all.

Nevertheless, thanks for asking 👍
