### ISSUE TITLE
Icon highlight when clicking

### ISSUE THREAD

**Issue by kayzee** [newmarcel/KeepingYouAwake#5]
First off, thanks for sharing this with the world.  Much appreciated.

One enhancement I'd like to suggest is to not highlight the icon when clicking to activate.  Caffeine just changes the icon when you click and only highlights when you option+click to view the menu.

**Comment by iberezovsky** [comment]
It would be great to disable blue highlight on clicking.

**Comment by seangaffney** [comment]
Would love to see this implemented as well. Thanks for the great reincarnation of Caffeine!

**Comment by 1aurabrown** [comment]
I agree!

**Comment by ealeksandrov** [comment]
+1 for removing blue highlight.
Maybe even for right click (menu) too, if it is not possible to handle both states.

**Comment by newmarcel** [comment]
There will be a secret preference to completely disable the blue highlight in the next minor update of the app (not 1.3.0 but possibly 1.3.1) Stay tuned :+1:
