### ISSUE TITLE
Activation on start of specific software

### ISSUE THREAD

**Issue by accatyyc** [newmarcel/KeepingYouAwake#52]
I mainly use KeepingYouAwake to have the screen stay activated during DJ sets. Since I usually use an external controller and never touch the computer, it will be very likely to turn the screen off (external controllers won't activate it again).

However, after a set it's not uncommon that I forget to turn it off, leave the computer and it drains the battery because it doesn't sleep.

It would be awesome if I could choose some softwares within the settings which will make KeepingYouAwake automatically activate/deactivate when these softwares are started/quit.

**Comment by thegcat** [comment]
http://www.controlplaneapp.com/ might be an alternative for you, it can start and stop stuff based on the running apps and/or connected devices. I can't remember if you can have the screen not power down directly in it or if you'd need to script kya though.

**Comment by accatyyc** [comment]
Thanks! I'll check it out.

I also think this issue could be solved if #43 was implemented, since then I could take care of this myself via a script.

**Comment by newmarcel** [comment]
Thanks for suggesting this feature, that's a pretty nice use case 👍. I like the idea but I prefer to not add this functionality to the app in the foreseeable future. You mentioned it already, that #43 might be a workaround for this wish.

I'm closing this issue now.

**Comment by accatyyc** [comment]
👍
