### ISSUE TITLE
Some translated strings not taken into account

### ISSUE THREAD

**Issue by rei-vilo** [newmarcel/KeepingYouAwake#55]
Some strings are not taken into account, even when translations are provided.

* Preferences tabs names
* Optional settings

![capture 2016-06-12 a 11 30 04](https://cloud.githubusercontent.com/assets/951776/15990392/4b5d1d36-3091-11e6-8487-71b9e2f610e3.png)

**Comment by newmarcel** [comment]
OK, thanks for reporting! I'll have a look and see what I can do there.

_Related to this translation effort:_ I intend to move the list of durations to `NSDateComponentsFormatter` so they don't have to be localized at all. This is a personal requirement I set for myself before merging translation-related PRs into `master`.
