### ISSUE TITLE
Icon is not as clear as caffeine

### ISSUE THREAD

**Issue by lewisthompson** [newmarcel/KeepingYouAwake#57]
I like the concept but it's really not as clear as caffeine.

**Comment by newmarcel** [comment]
Hi Lewis. What do you mean exactly? You don't like the Icon? Which one exactly: the menu bar icon or app icon, or both 😉?

In the end this topic is pretty much a matter of personal taste, isn't it? Since this is open source you are free to create a fork with alternative icons.

**Comment by ubermuda** [comment]
I think what OP means is that in Caffeine it's obvious when it's enabled because the cup is full of coffee. When I first launched KYA I was not sure whether it was enabled or not until I enabled it through the menu.

**Comment by tiiiecherle** [comment]
Hey, I was in the same situation that I really liked (and still do ;)) the application, but did not like the icon that much... So I sat down and tried a few drafts...

[https://github.com/newmarcel/KeepingYouAwake/wiki/Custom-Icons](https://github.com/newmarcel/KeepingYouAwake/wiki/Custom-Icons)

[https://github.com/tiiiecherle/KeepingYouAwake_Icons](https://github.com/tiiiecherle/KeepingYouAwake_Icons)

I personally use set number 9 for a year now and I´m very happy with it.

Perhaps you like it, too. If not, I also included the vector graphic draft files as a zip and you can create your own ;)

Hope that helps

**Comment by GitBruno** [comment]
It would be cool if you could choose a set in a preference tab.

**Comment by ckesc** [comment]
Maybe my icon is what you want
https://github.com/ckesc/KeepingYouAwake_icon_fillCup

**Comment by newmarcel** [comment]
I'm sorry, I won't change the icon in the forseeable future. Please have a look at this page to see how you can install a custom icon: https://github.com/newmarcel/KeepingYouAwake/wiki/Custom-Icons
