### ISSUE TITLE
"Allow the display to sleep" causes the laptop to sleep when NOT connected to AC

### ISSUE THREAD

**Issue by NeckBeardPrince** [newmarcel/KeepingYouAwake#58]
Looks like the change made in #25 is causing the screen to shut off and then allow the laptop to go to sleep when not plugged into power.

The flag being used seems to be wrong.

`-s      Create an assertion to prevent the system from sleeping. This assertion is valid only when system is running on AC power.`

**Comment by newmarcel** [comment]
I was using the `-s` assertion, but I've temporarily disabled this feature in the 1.4.1 pre-release. The advanced option caused too much confusion, see #67

**Comment by timkite** [comment]
Possibly you want the -i assertion instead?
The -s assertion should be safe for desktop-class Macs.
