### ISSUE TITLE
Context menu on option-click

### ISSUE THREAD

**Issue by grav** [newmarcel/KeepingYouAwake#59]
Hi there! Thanks for a great app! A bit of nit-picking :-)

Currently, KYA shows the context menu, when I ctrl-click on the icon.

The behaviour of all the other apps with menu icons that I've tried, show either the context menu or an alternative context menu on alt+click, while the behaviour on ctrl+click never differs from a regular click.

Maybe KYA could have the same behaviour for sake of consistency?

I've tried Dropbox, the Bluetooth icon, the WLan icon, the Battery icon and the Volume icon.

**Comment by alexandreleroux** [comment]
Hi Mikkel,

Good point IMO. I would not change the current ctrl-click behavior, but it does make sense for option-click to also invoke the KYA menu instead enabling/disabling KYA. Let's see what the devs think! :-) -- Alex

**Comment by newmarcel** [comment]
Nit-picking is highly appreciated 😁

Let me make sure I correctly understood, what you are suggesting: you want to change the ctrl+click behaviour to ⌥+click?

Let me see…

- I clicked a bit around in my menu bar and a lot of system icons and third-party apps have menus that appear on regular click, while KYA hasn't.
- ctrl+click on the Mac should behave like right click, so other apps like Dash _(which shows the main window on click)_ show a context menu. KYA does the same.
- ⌥+click on system menu bar items offers oftentimes a lot more details. That's a behaviour I could actually leverage for alternative menu items and shortcuts.

Can you think of additional actions that would appear in the menu on ⌥+click?

**Comment by grav** [comment]
Yes, ⌥+click instead of ctrl+click. 

You could argue, that ctrl+click should behave like ctrl+click normally does, ie, show a context menu. My experience was different regarding menubar icons, but sure, both Dash and Caffeine show context menus on ctrl+click, so I guess the choice is subjective :-)

**Comment by newmarcel** [comment]
⌥+click is now supported in the current `master`. I'll use this feature to show additional useful options in the future. Thanks again for the suggestion 👍
