### ISSUE TITLE
macOS Sierra: Does KeepingYouAwake Still Work?

### ISSUE THREAD

**Issue by rei-vilo** [newmarcel/KeepingYouAwake#60]
It looks like KeepingYouAwake no longer works with macOS _Sierra_.

**Comment by alexandreleroux** [comment]
Works me for. Can you provide details regarding what does not appear to work for you Rei?

**Comment by rei-vilo** [comment]
My MacBook goes to sleep even when KeepingYouAwake has been activated.

**Comment by marcus-cr** [comment]
Haven't had any issues, even after upgrading to Sierra. Perhaps a system or app configuration issue or outdated?

**Comment by newmarcel** [comment]
I use it every day and haven't noticed any regressions yet. Can you provide more details what doesn't work anymore?

**Comment by rei-vilo** [comment]
In many occasions, I activated `KeepingYouAwake` with period set to indefinitely, but the MacBook went on sleep.

It wasn't running on batteries, but powered with the AC adapter.

**Comment by bmy** [comment]
doesn't work here. 2015 mbpr, macos 10.12

**Comment by newmarcel** [comment]
OK, I'm running it on three differrent machines constantly without problems. Let's get to the root of the problem:

Can you check something for me, if you experience these problems?

- run KYA as you normally would _(make sure it's active)_
- open the `Activity Monitor` app; search for `caffeinate`, there must be exactly one entry _(that's the command line tool by Apple that powers the core functionality of the app)_
- open Preferences; go to Advanced. What preferences are enabled?
    - if some are enabled, please disable and _reset to default_ and check again if the problem persists

**Comment by rei-vilo** [comment]
Thank you for your help.

* There's one single instance of `caffeinate` on the `Activity Monitor`.
* The advanced options for KYA are

![capture 2016-10-19 a 20 14 00](https://cloud.githubusercontent.com/assets/951776/19531672/c71a96e4-9638-11e6-8c5f-fe7822f884f0.png)

**Comment by newmarcel** [comment]
Good, the `caffeinate` process is there, so we can narrow it down to the advanced prefs: I would recommend disabling the second of the advanced prefs: `Allow the display to sleep…`. If the problem still persists we can examine further…

**Comment by rei-vilo** [comment]
Thanks! I'll proceed with a new test and let you know.

**Comment by bmy** [comment]
My advanced checkboxes were all empty except updates/pre-release. I hit reset to default anyway and quit/restarted KYA. Laptop still sleeps. Rebooting now just in case that's required for preference change (although I don't think it changed) to stick. Also nuking the below before reboot just for kicks. If this has any bearing at all, I use brew cask to install/maintain KYA and 99% of my other GUI apps.

<img width="878" alt="screen shot 2016-10-19 at 15 27 45" src="https://cloud.githubusercontent.com/assets/908969/19534132/a482f860-9610-11e6-8d72-0b9a4cc95854.png">

**Comment by rei-vilo** [comment]
Unchecking  `Allow the display to sleep…` seems to have solved the problem.

**Comment by bmy** [comment]
I guess mine is working now too, although none of my Advanced checkboxes were checked in the first place. Maybe clearing some of my pre-Sierra files did it?
