### ISSUE TITLE
Remains Active After Lid Closed

### ISSUE THREAD

**Issue by marcus-cr** [newmarcel/KeepingYouAwake#61]
Hello,

I've noticed that when KYA is active and I close the lid to my MBP then KYA will remain activated when opened again. After leaving on overnight KYA while show the remaining time until deactivation as negative. This hasn't caused any issues with the laptop other than the timer being negative.

**Comment by newmarcel** [comment]
This sounds like the same issue as described in #68.
I will close this issue here and close the other ticket when this is fixed. Thanks for reporting 👍
