### ISSUE TITLE
Does not work if lid is closed

### ISSUE THREAD

**Issue by IdanAdar** [newmarcel/KeepingYouAwake#66]
@newmarcel,
In my ever lasting quest to find an alternative to NoSleep, I have now found KeepingYouAwake. It seems like it is not working, though...

My expectation is that once I close the MacBook's lid, whatever is running i.e. a TV show in iTunes, will continue running. In reality this does not happen.

I also tried your suggestion in https://github.com/newmarcel/KeepingYouAwake/issues/19#issuecomment-76626586 to run `defaults write info.marcel-dierkes.KeepingYouAwake.PreventSleepOnACPower -bool YES` but it does not seem to work.

Closing the lid puts the Mac to sleep instead of keeping it running.  
I have, of course, clicked on the icon in the Menubar as well as set it to "indefinitely".

I am using:

* v1.4.0 of KeepingYouAwake
* macOS Sierra 10.12.1
* MacBook Pro late 2013 (charger connected and working)

**Comment by IdanAdar** [comment]
It seems even the the `caffeinate` command in Terminal fails... Could this be a bug in the OS itself??

**Comment by jeffbyrnes** [comment]
@IdanAdar my expectation is the opposite, that even if KeepingYouAwake/`caffeinated` is active, closing the lid should sleep the unit.

There is one exception to the lid closure putting a Mac to sleep:

* The unit is connected to a power adapter
* The unit is connected to an external display

This has been the design for as long as I can recall, and, in fact, no extra software is needed to enjoy that behavior.

It appears that it _is_ possible to override the lid sleep (there is [ImsomniaX](http://semaja2.net/projects/insomniaxinfo/)), but I do not know how well that app works.

**Comment by IdanAdar** [comment]
InsomniaX, NoSleep, Caffein, ... all do this. Or used to do it.
If the Mac is connected to a power adapter, and the app is active, closing the lid does not put the machine to sleep... this doesn't work anymore.

**Comment by jeffbyrnes** [comment]
Sounds like a fundamental change to macOS. `¯\_(ツ)_/¯`

**Comment by newmarcel** [comment]
Hi, thanks for the suggestion!
I will probably never support this option because `caffeinate` doesn't support this. KYA uses `caffeinate` under the hood and as long as Apple doesn't remove the tool from macOS this won't change.

But if someone can point me to a "nice" macOS API that allows this behavior I will gladly implement this as _advanced_ feature 😉

**Comment by r3a1d3a1** [comment]
Could a virtual display be the solution?! 🤔
