### ISSUE TITLE
Sierra update 10.12.1, Mac sleeps now

### ISSUE THREAD

**Issue by dudesahn** [newmarcel/KeepingYouAwake#67]
Hi, 
I've noticed since updating to 10.12.1, Keeping You Awake no longer seems to work. I have it on, but my computer will now go to sleep on its own. I believe this is an issue that is new since I updated to 10.12.1, but I'm not entirely sure. 

Thanks!

**Comment by popod** [comment]
I have the same issue ! Not sure but it seems that this append since 10.12.0.

**Comment by RSully** [comment]
Possibly relevant: #60

**Comment by bmy** [comment]
sleep happening again for me on 10.12.2, possibly on 10.12.1 (although in the other thread about sierra my issue was somehow resolved at some point). thanks

**Comment by Roman2K** [comment]
Confirmed on 10.12.1 (on two Macs). At least with "Allow the display to sleep" on (haven't yet tested with it off).

**Comment by newmarcel** [comment]
To avoid this confusion I have temporarily removed the buggy _display sleep_ advanced option in 1.4.1. It might come back in the future.

Version 1.4.1 is now available as pre-release.
