### ISSUE TITLE
Won't start on boot

### ISSUE THREAD

**Issue by vasqu1cr** [newmarcel/KeepingYouAwake#69]
Yes, I have the 'Start at Login' box checked. Every time I restart my computer I have to reopen the application to use it. I don't have 'Activate on Launch' checked.

I have just checked it to see if that will be a work around.

**Comment by newmarcel** [comment]
This should usually work, but you can do this manually by dragging the app icon into

`System Preferences` → `Users & Groups` → click your Username → `Login Items` (drop into the list)
