### ISSUE TITLE
LSSharedFileList* methods are deprecated

### ISSUE THREAD

**Issue by Eitot** [newmarcel/KeepingYouAwake#75]
Apple deprecated the LSSharedFileList* methods in El Capitan. Are you still planning to separate functionality into a helper application?

**Comment by newmarcel** [comment]
I really wished, I could go down that route. I am aware of the deprecation, but creating and maintaining a helper app just for this little task requires too much time right now for no real benefit.

I will monitor all upcoming macOS releases though, to make sure the existing legacy API doesn't get removed by Apple.

Community contributions are also welcome regarding this topic… but only if they don't add an insane amount of code, external dependencies and don't increase the current app bundle size.
