### ISSUE TITLE
Support for 'About' pane localizations

### ISSUE THREAD

**Issue by alexandreleroux** [newmarcel/KeepingYouAwake#76]
Thanks @newmarcel for having implemented localizations (issue #20). Am I mistaken or the 'About' pane in the Preferences cannot be translated at the moment? If this si confirmed, then this ticket is a request for the About pane to be also translatable. Thanks! -- Alex

**Comment by Eitot** [comment]
The Credits.rtf file can be made localisable in Xcode. Then you can have separate versions for each language.

**Comment by newmarcel** [comment]
Maintaining translations for this file would be too tedious with the growing amount of localizations. The maintenance cost is simply too high compared to the gained value. So I prefer having this file English-only right now.
