### ISSUE TITLE
Safe to close screen?

### ISSUE THREAD

**Issue by AlecRust** [newmarcel/KeepingYouAwake#77]
If I'm closing my MacBook screen I tend to switch off KeepingYouAwake, I guess to prevent it trying to stay "awake" whilst the screen is closed.

I assume this is unnecessary, but can someone confirm this?

**Comment by gwerbin** [comment]
I have this question as well. I've heard that MacBooks are really supposed to go to sleep when the screen is closed to prevent dangerous heat build-up.

**Comment by janclarin** [comment]
Closed-display mode is a thing and is [supported by Apple](https://support.apple.com/en-ca/HT201834). I use this all the time with the caveat that the laptop is plugged in. You don't need KeepingYouAwake to achieve this.

**Comment by newmarcel** [comment]
Even when KeepingYouAwake is activated, your MacBook will still go to sleep when you close the lid. No need to quit the app.
