### ISSUE TITLE
crash on active/start

### ISSUE THREAD

**Issue by chinito** [newmarcel/KeepingYouAwake#8]
Turning "activate on launch" and "start at login" muliple times on and off crashes the app

21.11.14 11:11:37,056 KeepingYouAwake[10356]: Unbalanced call to enableRelaunchOnLogin: enableRelaunchOnLogin was called without a preceding call to disableRelaunchOnLogin

**Comment by newmarcel** [comment]
This crash bug should be fixed in v1.2.1.

**Comment by marcus-cr** [comment]
Updates?
