### ISSUE TITLE
NSStatusItem behavior property in macOS Sierra

### ISSUE THREAD

**Issue by Eitot** [newmarcel/KeepingYouAwake#82]
[NSStatusItem](https://developer.apple.com/reference/appkit/nsstatusitem) has a new `behavior` property in macOS Sierra. It lets the user drag the menu item out of the menu bar, either to hide/disable it or to quit the app. The latter should be useful for KYA.

**Comment by newmarcel** [comment]
This is now implemented and will ship with the next update. Thanks for pointing this feature out 👍
