### ISSUE TITLE
Feature request: Activate When Plugged into External Display

### ISSUE THREAD

**Issue by caseyWebb** [newmarcel/KeepingYouAwake#84]
Hi, this is absolutely a "nice to have but not necessary" thing. It would be nice if there was an option to enable automatically when an external display is plugged in and disabled when it's unplugged.

**Comment by lazyatom** [comment]
This would actually save me from quite a lot of reboots -- my Mac regularly crashes when connected to an external display and going to sleep -- disabling sleep only when connected to the display would resolve this perfectly.

**Comment by sturza** [comment]
Created an MR for this.
