### ISSUE TITLE
Feature request: Sleep computer

### ISSUE THREAD

**Issue by winterflags** [newmarcel/KeepingYouAwake#85]
I'm a KeepingYouAwake user, on the lookout for a menu bar app that can Sleep macOS with a quick mouse-press.

I then realized that KeepingYouAwake could be a good companion for this "inverse" use, perhaps a setting in the right-click menu to actually put the computer to sleep? (If indeed this can be done through a Menu bar app).

I know that I'd use it, but I'd like to hear your thoughts.

**Comment by alexandreleroux** [comment]
Hi @winterflags , Apple provides shortcuts for putting the display to sleep: https://support.apple.com/en-us/HT201236 I know that's not exactly what you asked for, but maybe this can help with your use case?

**Comment by winterflags** [comment]
Thanks, but I sometimes forget the correct keyboard command for putting the computer to sleep – and one doesn't accidentally want to Shutdown if the incorrect one is used (they are quite similar).

I'm looking for a GUI/mouse way to Sleep.

Currently I've got a Terminal `.command` on my Desktop containing `pmset sleepnow`.

**Comment by winterflags** [comment]
OT: 

I solved this using [Hammerspoon](http://www.hammerspoon.org/). Just letting people know if anyone else is searching for a solution and this feature doesn't make it through (perhaps the request is too much of an antonym to what KeepingYouAwake is about TBH).

Hammerspoon scripting is done via LUA:
```lua
-- Sleep Computer
menu_sleep = hs.menubar.new():setClickCallback(hs.caffeinate.systemSleep)
menu_sleep:setIcon(hs.image.imageFromPath('~/.hammerspoon/Icons/sleep.png'):setSize({w=16, h=16}))
-- Sleep Display
menu_displaysleep = hs.menubar.new():setClickCallback(function() hs.execute("pmset displaysleepnow") end)
menu_displaysleep:setIcon(hs.image.imageFromPath('~/.hammerspoon/Icons/led-display.png'):setSize({w=16, h=16}))
```

**Comment by newmarcel** [comment]
Thanks for providing a resolution yourself using `Hammerspoon` 👍. I will not add a specific sleep shortcut to the menu in the future.
