### ISSUE TITLE
Sleep not prevented when closing lid?

### ISSUE THREAD

**Issue by LennardF1989** [newmarcel/KeepingYouAwake#91]
So for some reason whenever I close the lid with KeepingYouAwake doesn't actually prevent sleep-mode. When I try to ping the Mac from a PC, it's unresponsive. Re-opening the lid also presents the login-screen. Checking the man-page of the tool this App wraps, it says the only requirement is having the AC-adapted plugged in, which I have.

Using InsomniaX this is not an issue.

I really like KeepingYouAwake for its simplicity. Is this an issue with KeepingYouAwake or Mac? Running Mac OS X 10.12.3.

**Comment by newmarcel** [comment]
KeepingYouAwake uses Apple's `caffeinate` command line tool. Caffeinate doesn't allow preventing sleep mode when the lid is closed — probably out of thermal concerns.

I can therefore say that this feature won't be supported unless `caffeinate` is updated sometime in the future.
