### ISSUE TITLE
Allow enterprises to disable specific length options

### ISSUE THREAD

**Issue by prbsparx** [newmarcel/KeepingYouAwake#95]
A lot of enterprises don't want to allow people to keep their screen awake indefinitely.

It would be great if there were preference options that allowed us to disable or enable specific lengths of time.

**Comment by newmarcel** [comment]
The next release will introduce the ability to fully customize the list of activation durations via user defaults. This should also allow you to customize the list using the `defaults` command line tool.

I hope this will satisfy your use case. Thanks for the suggestion and your patience 😃👍
